### ISSUE TITLE
Par1 in idL etc

### ISSUE THREAD

**Issue by conal** [conal/linalg#17]
I’ve been uncomfortable with the appearance of `Par1` in `idL` and (by contagion) everything that uses `idL` for a while, and it’s getting uglier as I go. The source of the `Par1` is the `Scale` in `rowMajor`:

``` haskell
-- | Row-major "matrix" of linear maps
rowMajor' :: (V2 f g, V2 h k) => k (h (L f g s)) -> L (h :.: f) (k :.: g) s
rowMajor' = Fork . fmap Join

-- | Row-major "matrix" of scalars
rowMajor :: (V f, V g) => g (f s) -> L (f :.: Par1) (g :.: Par1) s
rowMajor = rowMajor' . (fmap.fmap) Scale

diagR :: (Representable h, Eq (Rep h), Additive a) => h a -> h (h a)
diagR as =
  tabulate (\ i -> (tabulate (\ j -> if i == j then as `index` i else zero)))

idL :: (V f, Semiring s) => L (f :.: Par1) (f :.: Par1) s
idL = rowMajor (diagR (pureRep one))
```

Collections n-ary injections and projections can be extracted by unjoining and unforking (respectively) `idL`, but then they also get `Par1`.

I tried generalizing the `Scale` constructor from `s -> L Par1 Par1 s` to `s -> L f f s` [in a branch](https://github.com/conal/linalg/blob/d5cc2d5a0f66da02a786e20902dac4d2b12a1d92/src/LinAlg.hs#L55). The experiment was a mixed success, with some required changes looking better than others.

**Comment by conal** [comment]
I looked at how @bolt12 [implemented `id` in laop](https://github.com/bolt12/laop/blob/dd362e9523cd643981bb6c572e5aee3ed9220a26/src/LAoP/Matrix/Internal.hs#L481-L482), but I don’t see how to strip out the numbers (or lists). It’s important to me to keep the implementation very simple and general in anticipation of compiling to massively parallel back-ends (GPU, TPU, FPGA, photonic, etc), perhaps via compiling-to-categories. I hope to automatically replace the GADT representation with a correct-by-construction, efficient low-level array/memory representation as outlined in [*Data-Parallel Programming without Arrays*](http://conal.net/papers/data-parallel-programming-without-arrays).

**Comment by dwincort** [comment]
I actually really like the idea of changing `Scale` to `s -> L f f s` and then thinking of it as a scalar block, but I also see the issue you run into with `JoinL` and `ForkL` (the definitions of `ins` and `exs` cause infinite loops).  What about introducing a new constructor:
```haskell
  Diag  :: f s -> L f f s
```
Adding new cases to the pattern functions is straightforward:
```haskell
unjoin2 (Diag (s :*: s')) = (Diag s :&# Zero, Zero :&# Diag s')

unfork2 (Diag (s :*: s')) = (Diag s .@ exl, Diag s' .@ exr)

unforkL (Diag s)   = (.@ Diag s) <$> exs

unjoinL (Diag s)   = (Diag s .@) <$> ins
```
And definitions for `ins` and `exs` no longer need `unforkL` and `unjoinL`:
```haskell
ins = unjoinL (Diag $ pureRep one)
exs = unforkL (Diag $ pureRep one)
```
I also assume adding cases to `(+)` and `(.@)` won't be terribly difficult, and I'm guessing there are some nice linear algebra laws about diagonal structures that we can use.  And voila!  The new `Diag` construction works as a bridge between `Scale` and the other constructions, allowing `idL` to stay defined as `Scale one` but actually work.

---

That said, the above is all speculation right now because I haven't gotten the types to work out right.  The root problem seems to be that just because GHC knows `Representable (f :*: g)` doesn't mean it can deduce `(Representable f, Representable g)`, so my implementation effort is met with all sorts of "Could not deduce (Representable g1)" errors, and each time I just add the constraint, a new error seems to pop up somewhere else.  Maybe chasing down all the errors will yield a nice conclusion, but it might also just yield a big mess.

**Comment by dwincort** [comment]
Sigh, I think my above idea is not good enough.  I thought it would fix the problem of needing `Eq (Rep f)` and having an explicit diagonalization function, but I still can't get around the `unforkL` and `unjoinL` issue without such a function.  The only thing I can think of at this point is wondering if a "diagonalizable representable functor" is a thing worthy of study.

**Comment by bolt12** [comment]
I think it's good to think about every possible idea. I had to iterate
through some of them at some point for my paper "TYM" and am familiar with
some of the tradeoffs. I agree with what you said above. I eventually ended
up preferring for a simpler, minimal, less featured inductive type which is
more suitable for a functional pearl. Maybe this new approach by Conal can
lead us to other elegant, more featured design.

**Comment by conal** [comment]
Thanks for the suggestions\!

> the definitions of `ins` and `exs` cause infinite loops.

Hah\! I hadn’t noticed. Thanks.

``` haskell
unjoin2 (Diag (s :*: s')) = (Diag s :&# Zero, Zero :&# Diag s')

unfork2 (Diag (s :*: s')) = (Diag s .@ exl, Diag s' .@ exr)
```

And finish bringing out the product/coproduct duality:

``` haskell
unjoin2 (Diag (s :*: s')) = (inl .@ Diag s, inr .@ Diag s')
```

> 
> 
> ``` haskell
> data L :: (* -> *) -> (* -> *) -> (* -> *) where
>   Zero  :: V2 f g => L f g s
>   Scale :: V f => s -> L f f s
>   Diag  :: V f => f s -> L f f s
>   ...
> ```

With `Diag`, we could drop `Zero` and `Scale`.

Come to think of it, with just `Scale`, we could also drop `Zero`. Doing so interferes with some optimizations (currently used in `(+)` and `(.@)`). A simple solution is to add an `isZero`, as described in Section 2.5 of [*Generalized Convolution and Efficient Language Recognition*](http://conal.net/papers/convolution/). (Since `isZero` can be expensive or noncomputable, I left it out of `Additive`.) I guess we could reintroduce `Zero` as a pattern synonym, rather than a constructor.

**Comment by conal** [comment]
On the other hand, with just `Diag`, `isZero` will be more expensive.

Rewrite rules give an alternative to run-time pattern matching, though with less dependable results.

**Comment by conal** [comment]
> Come to think of it, with just `Scale`, we could also drop `Zero`.

No, we cannot, because `Zero` is more shape-polymorphic than `Scale`.

**Comment by conal** [comment]
I like the solution in PR #18, especially with the suggestions made there. Closing this issue.
